tc_enable: 1
tc_delay: 16
tc_loss: 16

mem_enable: 0
mem_occupy: 30000 #30G

disk_enable: 1
disk_write: 100 #100M/second
disk_occupy: 1000000 #1T

split_enable: 1
failover_enable: 1
transform_enable: 1


duration: 3600 #1hour
targets: ["redis@127.0.0.1:6379", "redis@127.0.0.1:6378"]

consul: '127.0.0.1:8500'
